// Code generated by Thrift Compiler (0.14.2). DO NOT EDIT.

package thriftexample

import(
	"bytes"
	"context"
	"fmt"
	"time"
	"github.com/apache/thrift/lib/go/thrift"
	"speed-test/pkg/thrifttimestamp"

)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = time.Now
var _ = bytes.Equal

var _ = thrifttimestamp.GoUnusedProtection__

func init() {
}

